# Generated by Django 3.2.16 on 2022-12-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talle', models.IntegerField(max_length=2)),
                ('color', models.CharField(max_length=50)),
                ('lisa', models.BooleanField(verbose_name='Remera Lisa')),
                ('genero', models.IntegerField(max_length=1)),
            ],
        ),
    ]
