# Generated by Django 5.1.7 on 2026-04-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0002_auto_20221215_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ropa',
            name='genero',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ropa',
            name='lisa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ropa',
            name='talle',
            field=models.IntegerField(),
        ),
    ]
